### ISSUE TITLE
Campaign and Claim Sector Labels

### ISSUE THREAD

**Issue by Folset** [pnunes/Hexterminate#10]
This is more of a design suggestion than an issue:
![mapcolour](https://cloud.githubusercontent.com/assets/9412444/12668714/157939fa-c662-11e5-85c9-0a6d871f00b7.PNG)

Change the colour of the Campaign label so that you can easily identify which is the campaign and which is a claim sector mission.

**Comment by pnunes** [comment]
Changed it so the Campaign label is in Imperial blue. It will make it easier to spot as there will be a few more events active in the galaxy view.
