### ISSUE TITLE
Game freezes for a moment after entering battle from fresh start

### ISSUE THREAD

**Issue by Folset** [pnunes/Hexterminate#11]
If you start the game up from windows then go into a game, new or loaded, then go into a system, after about 20-40 seconds after you jump in the game will freeze for a moment and then continue as normal.

I ran a few tests to see if it was related to tutorial, (wasn't) or dialogue (don't think so) it might be something that has to load up for the first time and is then loaded throughout the play session, as it doesn't seem to do it again in following battles.

**Comment by pnunes** [comment]
The new shader caching system has fixed this. Will be part of the 0.7.4 release.
