### ISSUE TITLE
Three ships can't kill one because of tactics issue

### ISSUE THREAD

**Issue by Folset** [pnunes/Hexterminate#20]
So I bugged out and couldn't shoot at people any more because I went off the Z axis, then this happened while waiting for my fleet to kill the remaining enemies.
![cantkill](https://cloud.githubusercontent.com/assets/9412444/12791417/c0839c72-caaf-11e5-8b2a-d3426a0e5343.PNG)
So what's happening here is that they can't kill the one enemy ship because it keeps repairing itself, and they don't stop circling to focus fire on one module. BUT he stays still and keeps hitting them with torps, so they are slowly getting destroyed.

As I am typing this, reinforcements have arrived to hopefully resolve the issue.

**Comment by pnunes** [comment]
I believe that's fine. The fleet is supposed to essentially provide fire support and additional targets for enemies to shoot but essentially the player is the one that has to deal with the focus firing specific modules (such as taking out engines / reactors). If the player is entirely absent, as in this case, that result is OK.

**Comment by Folset** [comment]
Fair point. I guess it was because I couldn't do anything and was frustrated. Such is pre-release :D
