### ISSUE TITLE
Game Crashed when I died

### ISSUE THREAD

**Issue by Folset** [pnunes/Hexterminate#21]
So I got blown up on Hardcore and then the game crashed.
![wentbang](https://cloud.githubusercontent.com/assets/9412444/12791714/126e0ac6-cab1-11e5-87e0-37ddc4f06385.PNG)
[log.txt](https://github.com/pnunes/Hexterminate/files/116119/log.txt)

**Comment by pnunes** [comment]
Should be fixed in 0.8.0.
