### ISSUE TITLE
Fleet ship keeps firing when enemy is already dead.

### ISSUE THREAD

**Issue by Folset** [pnunes/Hexterminate#26]
Irfanview seems to have made the image go weird after resizing.. Sorry for melting your screen and/or eyeballs.

![keepfiring](https://cloud.githubusercontent.com/assets/9412444/13195807/f5b91e14-d7c3-11e5-9343-69f91957f3e8.PNG)

**Comment by pnunes** [comment]
Fixed in 0.8.0.
