### ISSUE TITLE
UI/UX: Tooltips

### ISSUE THREAD

**Issue by Folset** [pnunes/Hexterminate#3]
**Problem:** Quite difficult to know what some things are, the actionbar icons for example. I have no idea what that cog does until I get to a docking station.

**Possible Solution:** Have some tooltips that pop up when you hover over them.

**Comment by pnunes** [comment]
The key text now gets replaced with the module's name when the player hovers the icon, which should do the trick!

![tooltip](https://cloud.githubusercontent.com/assets/1248288/12685010/c11c8fd0-c6b9-11e5-89aa-20afe185ae99.png)
