### ISSUE TITLE
Balance: Phase Barrier

### ISSUE THREAD

**Issue by Folset** [pnunes/Hexterminate#4]
I think that the Phase Barrier is maybe a little bit too overpowered at the moment. It can stop ANYTHING and all you need to do is sort of sit there. This could probably be balanced further with changing how much energy it drains or something, but I have another possible solution.

Shorten it.
![barrier 5](https://cloud.githubusercontent.com/assets/9412444/12551454/34b2f370-c373-11e5-88e7-7d15e9de1fd2.PNG)

You now have to focus more on incoming fire, where as before, whoever you were shooting at, simply couldn't hit you.

A rare drop could probably have a larger barrier, making it more powerful and feel like a rare drop.

**Comment by pnunes** [comment]
Agreed, it is too wide right now. I've reduced its width from 120m to 90m. There are other phase barrier modules in-game (rarer drops) which have greater coverages but have also had their values adjusted. Those changes will be available on 0.7.3.
