### ISSUE TITLE
Bug: Action bar changes order when going into a new system

### ISSUE THREAD

**Issue by Folset** [pnunes/Hexterminate#5]
When leaving dock:
![abar before](https://cloud.githubusercontent.com/assets/9412444/12566023/301370d6-c3c0-11e5-9bc6-89b0930b2eb2.PNG)

When entering a new system:
![abar after](https://cloud.githubusercontent.com/assets/9412444/12566030/39331c5c-c3c0-11e5-918a-7a2e9084dfb0.PNG)

**Comment by pnunes** [comment]
The icons are now automatically sorted by name, which has fixed this issue.
