### ISSUE TITLE
Dialogue not being removed and overlapping 

### ISSUE THREAD

**Issue by Folset** [pnunes/Hexterminate#8]
![dialogue1](https://cloud.githubusercontent.com/assets/9412444/12668524/3e073824-c660-11e5-9a07-ce111acf96fe.PNG)
How to replicate:
1. Start new game with tutorial
2. Click to continue through everything
3. Wait for dialogue box to open
4. Exit to main menu then start a new game
5. Shake fist at bug

**Comment by pnunes** [comment]
Thanks, I've fixed this. It will be available on 0.7.3.
